# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 5.2.17.
# """


# from pathlib import Path
# import os
# import dj_database_url
# from dotenv import load_dotenv

# load_dotenv()

# # ============================================================
# # BASE DIRECTORY
# # ============================================================

# BASE_DIR = Path(__file__).resolve().parent.parent


# # ============================================================
# # SECURITY
# # ============================================================

# SECRET_KEY = os.getenv(
#     "DJANGO_SECRET_KEY",
#     "unsafe-development-key",
# )

# DEBUG = os.getenv("DEBUG", "False") == "True"

# # ALLOWED_HOSTS = [
# #     "localhost",
# #     "127.0.0.1",
# #     "https://gamani-ems.onrender.com/login",
# # ]
# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     "gamani-ems.onrender.com",
# ]


# # ============================================================
# # CUSTOM USER MODEL
# # ============================================================

# AUTH_USER_MODEL = "accounts.User"


# # ============================================================
# # APPLICATIONS
# # ============================================================

# INSTALLED_APPS = [
#     # Django
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     # Third-party
#     "rest_framework",
#     "django_filters",
#     "corsheaders",
#     "rest_framework_simplejwt.token_blacklist",

#     # Local apps
#     "accounts",
#     "employees",
#     "tasks",
#     "attendance",
#     "breaks",
#     "work_reviews",
#     "salaries",
#     "notifications",
# ]


# # ============================================================
# # MIDDLEWARE
# # ============================================================

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",

#     # CORS should be near the top
#     "corsheaders.middleware.CorsMiddleware",

#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]


# # ============================================================
# # CORS
# # ============================================================

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",

#     # Replace this with your actual Render frontend URL
#     "https://gamani-ems.onrender.com/login",
# ]


# # ============================================================
# # CSRF
# # ============================================================

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5173",

#     # Replace this with your actual Render frontend URL
#     "https://gamani-ems.onrender.com/login",
# ]


# # ============================================================
# # URL CONFIGURATION
# # ============================================================

# ROOT_URLCONF = "config.urls"


# # ============================================================
# # TEMPLATES
# # ============================================================

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]


# # ============================================================
# # WSGI
# # ============================================================

# WSGI_APPLICATION = "config.wsgi.application"


# # ============================================================
# # DATABASE - MYSQL
# # ============================================================

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",

#         "NAME": os.getenv(
#             "MYSQL_DATABASE",
#             "employee_work_management",
#         ),

#         "USER": os.getenv(
#             "MYSQL_USER",
#             "root",
#         ),

#         "PASSWORD": os.getenv(
#             "MYSQL_PASSWORD",
#             "",
#         ),

#         "HOST": os.getenv(
#             "MYSQL_HOST",
#             "127.0.0.1",
#         ),

#         "PORT": os.getenv(
#             "MYSQL_PORT",
#             "3306",
#         ),

#         "OPTIONS": {
#             "charset": "utf8mb4",
#         },
#     }
# }


# # ============================================================
# # DJANGO REST FRAMEWORK
# # ============================================================

# REST_FRAMEWORK = {
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.IsAuthenticated",
#     ],

#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         (
#             "rest_framework_simplejwt.authentication"
#             ".JWTAuthentication"
#         ),
#     ],

#     "DEFAULT_FILTER_BACKENDS": [
#         "django_filters.rest_framework.DjangoFilterBackend",
#         "rest_framework.filters.SearchFilter",
#         "rest_framework.filters.OrderingFilter",
#     ],

#     "DEFAULT_PAGINATION_CLASS": (
#         "core.pagination.StandardPagination"
#     ),

#     "PAGE_SIZE": 20,

#     "EXCEPTION_HANDLER": (
#         "core.exceptions.custom_exception_handler"
#     ),
# }


# # ============================================================
# # PASSWORD VALIDATION
# # ============================================================

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "UserAttributeSimilarityValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "MinimumLengthValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "CommonPasswordValidator"
#         ),
#     },
#     {
#         "NAME": (
#             "django.contrib.auth.password_validation."
#             "NumericPasswordValidator"
#         ),
#     },
# ]


# # ============================================================
# # INTERNATIONALIZATION
# # ============================================================

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # ============================================================
# # STATIC FILES
# # ============================================================

# STATIC_URL = "/static/"

# STATIC_ROOT = BASE_DIR / "staticfiles"


# # ============================================================
# # MEDIA FILES
# # ============================================================

# MEDIA_URL = "/media/"

# MEDIA_ROOT = BASE_DIR / "media"
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "unsafe-development-key",
)

DEBUG = os.getenv("DEBUG", "False").lower() == "true"


# ============================================================
# ALLOWED HOSTS
# ============================================================

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Render automatically provides this hostname
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Optional manually configured backend hostname
RENDER_BACKEND_HOST = os.getenv("RENDER_BACKEND_HOST")

if RENDER_BACKEND_HOST:
    ALLOWED_HOSTS.append(RENDER_BACKEND_HOST)


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "accounts.User"


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # --------------------------------------------------------
    # Django
    # --------------------------------------------------------

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # --------------------------------------------------------
    # Third-party
    # --------------------------------------------------------

    "rest_framework",
    "django_filters",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",

    # --------------------------------------------------------
    # Local applications
    # --------------------------------------------------------

    "accounts",
    "employees",
    "tasks",
    "attendance",
    "breaks",
    "work_reviews",
    "salaries",
    "notifications",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise serves static files in production
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # CORS
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# CORS
# ============================================================

CORS_ALLOWED_ORIGINS = [

    # Local React development
    "http://localhost:5173",

    # Production React frontend
    "https://gamani-ems.onrender.com",
]


# Allow additional origins from Render environment variable
# Example:
#
# CORS_ALLOWED_ORIGINS=https://example.com,https://example2.com

cors_origins = os.getenv("CORS_ALLOWED_ORIGINS")

if cors_origins:
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in cors_origins.split(",")
        if origin.strip()
    ]


# ============================================================
# CSRF
# ============================================================

CSRF_TRUSTED_ORIGINS = [

    # Local frontend
    "http://localhost:5173",

    # Production frontend
    "https://gamani-ems.onrender.com",
]


# ============================================================
# ROOT URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "config.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

"""
LOCAL DEVELOPMENT
-----------------

Uses MySQL:

MYSQL_DATABASE
MYSQL_USER
MYSQL_PASSWORD
MYSQL_HOST
MYSQL_PORT


RENDER PRODUCTION
-----------------

Uses PostgreSQL through:

DATABASE_URL

Render automatically provides DATABASE_URL when the
PostgreSQL database is connected to the Web Service.
"""


DATABASE_URL = os.getenv("DATABASE_URL")


if DATABASE_URL:

    # --------------------------------------------------------
    # RENDER / PRODUCTION
    # --------------------------------------------------------

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }

else:

    # --------------------------------------------------------
    # LOCAL DEVELOPMENT - MYSQL
    # --------------------------------------------------------

    DATABASES = {

        "default": {

            "ENGINE": "django.db.backends.mysql",

            "NAME": os.getenv(
                "MYSQL_DATABASE",
                "employee_work_management",
            ),

            "USER": os.getenv(
                "MYSQL_USER",
                "root",
            ),

            "PASSWORD": os.getenv(
                "MYSQL_PASSWORD",
                "",
            ),

            "HOST": os.getenv(
                "MYSQL_HOST",
                "127.0.0.1",
            ),

            "PORT": os.getenv(
                "MYSQL_PORT",
                "3306",
            ),

            "OPTIONS": {

                "charset": "utf8mb4",
            },
        }
    }


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {

    "DEFAULT_PERMISSION_CLASSES": [

        "rest_framework.permissions.IsAuthenticated",
    ],

    "DEFAULT_AUTHENTICATION_CLASSES": [

        (
            "rest_framework_simplejwt.authentication"
            ".JWTAuthentication"
        ),
    ],

    "DEFAULT_FILTER_BACKENDS": [

        "django_filters.rest_framework.DjangoFilterBackend",

        "rest_framework.filters.SearchFilter",

        "rest_framework.filters.OrderingFilter",
    ],

    "DEFAULT_PAGINATION_CLASS": (
        "core.pagination.StandardPagination"
    ),

    "PAGE_SIZE": 20,

    "EXCEPTION_HANDLER": (
        "core.exceptions.custom_exception_handler"
    ),
}


# ============================================================
# SIMPLE JWT
# ============================================================

from datetime import timedelta


SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=30
    ),

    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=1
    ),

    "ROTATE_REFRESH_TOKENS": False,

    "BLACKLIST_AFTER_ROTATION": True,

    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": "HS256",

    "SIGNING_KEY": SECRET_KEY,

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# WhiteNoise compressed static files
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:

    # HTTPS / Render
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    # Browser security
    SECURE_SSL_REDIRECT = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"


# ============================================================
# LOGGING
# ============================================================

LOGGING = {

    "version": 1,

    "disable_existing_loggers": False,

    "handlers": {

        "console": {

            "class": "logging.StreamHandler",
        },
    },

    "root": {

        "handlers": ["console"],

        "level": "INFO",
    },
}

# # ============================================================
# # DEFAULT PRIMARY KEY
# # ============================================================

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
