# Generated by Django 5.2.17 on 2026-08-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_month", models.DateField()),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "performance_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_salary_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_records",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-salary_month"],
                "indexes": [
                    models.Index(
                        fields=["employee", "salary_month"],
                        name="salaries_sa_employe_9cb996_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "salary_month"),
                        name="unique_employee_salary_month",
                    )
                ],
            },
        ),
    ]
